apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: dev
  labels:
    app: frontend-app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/subnets: subnet-0d4f5ab5525665f2c,subnet-0a331faca6bd54737
    alb.ingress.kubernetes.io/security-groups: sg-053e418cf068d5134,sg-0c936538f04f1cb17
    ## An internal ALB uses private subnets, external uses public subnets
    ##dont forget to add SG formed automatically with the description(EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads) or maybe try tagging as the picture says
    #ssl settings
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:331879450537:certificate/783ac79c-8b6d-460e-bfcc-bd587c4aad10
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    #ssl redirect setting  #This particular input redirects all http traffic to https
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
    #- host: www.joashtech.link
    - http:
        paths: 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80     